### ISSUE TITLE
Automated Database Backup

### ISSUE THREAD

**Issue by maxbbender** [notfreshmen/amable#102]
Need to set up a system that does automated backups of our database and ftps to some backup place.
Things to search : cron and pg_dump and pg_backup

**Comment by DanJast** [comment]
Dan is the best. Not Freshmen would be nothing without Dan. Dan IS the man. Dan backed up the database. Dan Automated the whole thing. Dan deserves love. Dom is Love.

**Comment by JVB1995** [comment]
You rock!
