### ISSUE TITLE
My Account Page

### ISSUE THREAD

**Issue by maxbbender** [notfreshmen/amable#24]
Show the users account. All properties of the User(see ER) should be editable and changed. Validation on these fields for correct input (regex for emails, valid password if changing for whatever requirements we have, ect.). 

Features:
- Edit any details of their personal information
- See the communities they are a part of
- Leave a community they are a part of
- See the posts for each individual community
- See all of their posts for all communities
- TBA

**Comment by ethnt** [comment]
Closed with #73.
