### ISSUE TITLE
Search Communities Page

### ISSUE THREAD

**Issue by maxbbender** [notfreshmen/amable#25]
So, our Users need to be able to see, sort and filter all communities and then an easy button for them to join said community. Implement a search of existing communities with a search bar that will auto fill user input on key press. Users should be easily able to see details and statistics about the communities.

Features
- Link to Petition New Community Page

- Community exists, just a hyperlink to the community
- Community pending, yellow mark with option to up vote
- Community doesn’t exist, petition to create button. Creates the community into a pending form for admins to approve to existing or denied.

**Comment by maxbbender** [comment]
`/communities` and `/communities/view` needs style

**Comment by maxbbender** [comment]
on `/communities` (search) we should have a collapsable section for "my communities", collapsed by default

**Comment by maxbbender** [comment]
on `/communities` as the user searches : If the community they are searching for is not active yet (doesn't have more then 10 upvotes) we need to increase. May need to create a join table so users can't vote twice. If the community doesn't exist there needs to be a button to "propose to create" the community. At which point a new community will be created and inserted into the database with 1 vote (the vote from the user who created it)

**Comment by ethnt** [comment]
Going to change the search from what I changed it to (JS filtering) back to what Max had. Need to figure out better way to output HTML though.

**Comment by maxbbender** [comment]
Meeting 11/14 : 
- Need implement if not exists, make button petition
  -- Create Community
  -- Create Community Upvote
- Community Exists but is not active

**Comment by maxbbender** [comment]
Done above, just need some style now

**Comment by maxbbender** [comment]
Style Needed

- [x] Better was to show if you voted or not. This could be a `red X` if you haven't voted yet, `yellow ~` if you have voted for it (but not approved yet) and `green check` if the community is active

- [x] Need some descriptors on the top search bar

- [x] Need a button to click to join community if the community is active and if you aren't already a part of the community

- [ ] Need two sections, the first is the communities that you are a part of already. This should be collapsible so you can only see ones that you aren't a part of. The second section contains communities you aren't a part of

**Comment by ethnt** [comment]
Closed with #128.
