### ISSUE TITLE
User Home Page

### ISSUE THREAD

**Issue by maxbbender** [notfreshmen/amable#26]
Once they are logged in they will be taken to their home page.  This will abide by the order defined by Pablo as far as what shows first. 

Order goes as follows
1. People user follows
2. Post from Communities user follows
3. Suggested Communities? [idk]
4. All posts from all communities

Post Actions
- reply to post ( give kindness)
- reply to reply (inception)
- upvote post
- upvote reply? (are we doing it reddit style)
- report post
  -- dialogue or option list pops down to either give a reason or user input a reason to report

Other Features
- Link to [Search Communities](https://github.com/notfreshmen/amable/issues/25) Page
- Provide Feedback/Report a problem

**Comment by JVB1995** [comment]
Are we reporting replies as well? Hadn't really thought about that as an issue.

**Comment by maxbbender** [comment]
Not sure, something to ask Pablo maybe next week.

**Comment by maxbbender** [comment]
@pablorp80 any thoughts?

**Comment by pablorp80** [comment]
You could give the posting-user the power to manage replies to a prayer request: e.g. delete an offensive reply.

**Comment by JVB1995** [comment]
I like that idea, adds another layer of filtering.

**Comment by maxbbender** [comment]
closed in favor of #36
