### ISSUE TITLE
Dashboard page

### ISSUE THREAD

**Issue by ethnt** [notfreshmen/amable#36]
- [ ] Post ordering
  1. People user follows
  2. Post from Communities user follows
  3. Suggested Communities? [idk]
  4. All posts from all communities
- [ ] Post actions
  - [x] Reply to post (give kindness)
  - [x] Reply to reply (inception)
  - [x] Upvote post
  - [ ] Upvote reply? (are we doing it reddit style)
  - [x] Report post
    - [x] Dialogue or option list pops down to either give a reason or user input a reason to report
- [ ] Other Features
  - [ ] Provide feedback/report a problem

**Comment by maxbbender** [comment]
see above for specs for page.

**Comment by ethnt** [comment]
Here's a checklist:

- [ ] Post ordering
  1. People user follows
  2. Post from Communities user follows
  3. Suggested Communities? [idk]
  4. All posts from all communities
- [ ] Post actions
  - [ ] Reply to post (give kindness)
  - [ ] Reply to reply (inception)
  - [ ] Upvote post
  - [ ] Upvote reply? (are we doing it reddit style)
  - [ ] Report post
    - [ ] Dialogue or option list pops down to either give a reason or user input a reason to report
- [ ] Other Features
  - [ ] Provide feedback/report a problem

**Comment by maxbbender** [comment]
The dashboard "Make a Post" section needs a better dropdown style for selecting which community to post in.

**Comment by maxbbender** [comment]
do not show posts that have been answered on dashboard. But show it on the "View Communities" page

**Comment by maxbbender** [comment]
So show top posts from all communities even if you don't belong. But you can't reply to posts if they are in a community you don't belong.

**Comment by maxbbender** [comment]
Views
- Communities you Follow
- Top Posts
- Posts from people you follow

**Comment by ethnt** [comment]
Rating of posts is top _n_ upvotes per day.
