### ISSUE TITLE
Use single table inheritance for reports

### ISSUE THREAD

**Issue by ethnt** [notfreshmen/amable#39]
We should probably make the reports use [single table inheritance](http://docs.sqlalchemy.org/en/latest/orm/inheritance.html#single-table-inheritance). Basically we'd have a `reports` database with a `type` column and a `Report` model. Then we'd have `PostReport`, `CommentReport`, and `UserReport` models that inherit from `Report`. This way we don't have to have completely separate tables for each kind of report with virtually the same columns.

**Comment by maxbbender** [comment]
I like it. Is there anything that is different(column wise) between all those types of reports?

**Comment by ethnt** [comment]
No, not really. They all have `content`, `user_id` (for the author), `kind`, etc. The only thing that'd need to change would be how to make the relationship to the parent, so we'd need to have some kind of polymorphic relationship.

**Comment by maxbbender** [comment]
hmm, I was looking at those.
