### ISSUE TITLE
factory_boy isn't actually creating records

### ISSUE THREAD

**Issue by ethnt** [notfreshmen/amable#54]
So... I'm not sure how long this has been like this, but in tests factory_boy isn't actually creating records. I'm just now noticing because of constraints on other table's columns.

```
>>> from spec.factories.post_factory import PostFactory
>>> PostFactory.create()
<Post None>
```

**Comment by maxbbender** [comment]
is this fixed by using the session.commit() now? @ethnt

**Comment by maxbbender** [comment]
fixed
