### ISSUE TITLE
Third normal form

### ISSUE THREAD

**Issue by ethnt** [notfreshmen/amable#57]
Ensure we're in 3NF.

**Comment by maxbbender** [comment]
No transitive dependency. We have abstracted out hashtags and communities. Only place that I can see that would have that issue. @ethnt @JVB1995 take a look at this https://github.com/notfreshmen/amable/blob/master/docs/erd.pdf and if you don't see anything I think we are good to close this.

**Comment by maxbbender** [comment]
Database is in 3NF
