### ISSUE TITLE
Hashed passwords don't contain a colon

### ISSUE THREAD

**Issue by ChrisCordaro** [notfreshmen/amable#62]
Hey Max. Just doing some work here and Ethan and I seem to have stumbled upon a small issue. When we try to validate a users password upon a login attempt, we're getting the error 'ValueError: not enough values to unpack (expected 2, got 1)'. It seems that the stored passwords are colon-less (which sounds like a person problem) and the "check_password" function in password.py is looking to split  a users stored password by the colon, which is missing.

**Comment by maxbbender** [comment]
Ok Ill take a look at it

**Comment by maxbbender** [comment]
Did you push your changes for this @ChrisCordaro ?

**Comment by ChrisCordaro** [comment]
Yea should be on the login branch
