### ISSUE TITLE
IT DOD requirements.

### ISSUE THREAD

**Issue by JVB1995** [notfreshmen/amable#63]
After reviewing the DOD requirements we are curious about what other requirements they need besides basic permissions and security. Our server only has two users, root and the amable user who's permissions do not violate DOD. And we have SELinux set up for further security. A discussion about these security standards and any further action that needs to be taken will be beneficial

**Comment by maxbbender** [comment]
@DanJast figured this out. Box is secured w/ only thing to fix is securing accounts with strong passwords.
