### ISSUE TITLE
Authorization system

### ISSUE THREAD

**Issue by ethnt** [notfreshmen/amable#67]
We should probably set up a simple _authorization_ (not _authentication_) system where we can ensure that the current user can perform an action on a resource. My proposal is to add the following methods to each model:
- `viewable_by`
- `creatable_by`
- `updatable_by`
- `destroyable_by`

Each of these methods would take in a `User`, and would return `True` or `False` on whether they can perform that action on the resource.

**Comment by maxbbender** [comment]
Sounds good with me. Lmk if you need help/want me to do it.
